dist: trusty
language: php

cache:
  directories:
    - vendor
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

env:
  global:
    - WP_VERSION=trunk

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=trunk
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=3.7
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
      env: WP_VERSION=5.1
    - php: 5.4
      env: WP_VERSION=5.0
    - php: 5.3
      env: WP_VERSION=4.9
      dist: precise
    - php: 5.2
      env: WP_VERSION=5.1
      dist: precise
    - php: 5.2
      env: WP_VERSION=4.0
      dist: precise
    - php: "7.4snapshot"
    - php: "nightly"

  allow_failures:
    - php: "7.4snapshot"
    - php: nightly

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  - |
    bash phpunit/install.sh wordpress_test root '' localhost $WP_VERSION
    if [[ "$TRAVIS_PHP_VERSION" != "5.2" ]]; then
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    else
      echo "PHP 5.2: Skipping composer for PHPUnit, relying upon builtin PHPUnit."
    fi

script:
  - |
    phpunit
    WP_MULTISITE=1 phpunit
