name: Bump Version

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Version part to bump"
        type: choice
        required: true
        options:
          - patch
          - minor
          - major
        default: patch

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    name: Bump ${{ inputs.release_type }} version and open PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run bump script
        id: bump
        run: |
          composer run bump-version -- ${{ inputs.release_type }}
          # Extract new version from src/readme.txt Stable tag
          NEW_VERSION=$(grep -Eo "^Stable tag:\s*[0-9]+\.[0-9]+\.[0-9]+" src/readme.txt | awk '{print $3}')
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore: Bump version to ${{ steps.bump.outputs.new_version }}"
          commit-message: "chore: bump version to ${{ steps.bump.outputs.new_version }}"
          body: |
            This PR was auto-generated by the Bump Version workflow.
            - Release type: `${{ inputs.release_type }}`
            - New version: `${{ steps.bump.outputs.new_version }}`
          branch: chore/bump-version-${{ steps.bump.outputs.new_version }}
          delete-branch: true
          add-paths: |
            wordpress-importer.php
            src/wordpress-importer.php
            src/readme.txt


