name: E2E Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]
    runs-on: ubuntu-latest
    name: E2E Tests (shard ${{ matrix.shard }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Setup latest Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Playwright and deps
        run: |
          npm --version
          node --version
          npm install -D @playwright/test@latest playwright@latest
          npx playwright install-deps

      - name: Run E2E tests
        run: composer run e2e -- --shard=${{ matrix.shard }}/3

